### PR TITLE
Add Swift dependencies to dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Swift ecosystem https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#swift

I am unsure if / how this will work but hopefully
https://github.com/bolsinga/site/blob/483e0f8dca65fe79c9fb2e0b9040c118e92c344f/Package.swift#L20
will be upgraded https://github.com/apple/swift-argument-parser/releases

### CODE REVIEW

**Comment by bolsinga** [comment]
Thanks; let's see what happens. :)

**Comment by bolsinga** [comment]
Maybe it's because it previously specified a specific version?

**Comment by cclauss** [comment]
Normally it should recommend an update even if the version is pinned.

I do not understand the `Non-Declarative Manifests` lingo at
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#swift

**Comment by bolsinga** [comment]
https://github.com/apple/swift-evolution/blob/7003da1439ad60896ec14657dfce829f04b0632c/proposals/0301-package-editing-commands.md?plain=1#L74 it says literals are ok, and that's a string literal. have you applied this swift dependabot before?

**Comment by cclauss** [comment]
I have never applied this Swift dependabot before.

**Pull request merged**
